services:
  react-weather:
    build:
      context: .
    container_name: weatherApp
    ports:
      - "3000:3000"
    volumes:
      - /app/weatherApp/node_modules
      - ./weatherApp:/app/weatherApp:cached

    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
